const {
  NODE_ENV,
  SERVICE_NAME,
  SERVICE_PORT,
  SERVICE_VERSION,
  QR_EXPIRE_MINS,
  BASIC_AUTH_USERNAME,
  BASIC_AUTH_PASSWORD,
  SERVER_DOMAIN,
  SENTRY_ENDPOINT,
} = process.env;

export default {
  NODE_ENV,
  SERVICE_NAME,
  SERVICE_PORT,
  SERVICE_VERSION,
  QR_EXPIRE_MINS,
  SERVER_DOMAIN,
  BASIC_AUTH_USERNAME,
  BASIC_AUTH_PASSWORD,
  SENTRY_ENDPOINT,
};
