version: '3.8'

services:
  mroi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  ffmpeg_cache: