version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173" # Map Vite's development server port
    env_file:
      - .env
    volumes:
      - .:/app # Mount the current directory to the container
      - /app/node_modules # Avoid overwriting node_modules
    # stdin_open: true
    # tty: true